
services:
  db:
    image: mysql:8.0.33-debian
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: php_backend
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: vue_frontend
    ports:
      - "${VUE_PORT}:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db_data:
